export default {
  // BussinessListItem
  Container: {
    padding: 10,
    backgroundColor: "#ffffff",
    borderRadius: 15,
    marginBottom: 15,
    display: "flex",
    flexDirection: "row",
    gap: 15,
  },
  subContainer: {
    display: "flex",
    gap: 8,
  },
  Img: {
    width: 100,
    height: 100,
    borderRadius: 15,
  },

  // BUsiness Details Screen
  detailbtn: {
    position: "absolute",
    zIndex: 10,
    padding: 20,
  },
  detailInfoContainer: {
    padding: 20,
    display: "flex",
    gap: 7,
  },
  detailSubContainer: {
    display: "flex",
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  messageBtn: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  bookingBtn: {
    padding: 13,
    backgroundColor: "#7722b2",
    borderWidth: 1,
    borderColor: "#7722b2",
    borderRadius: 99,
    flex: 1,
  },

  // BookingModal
  dateContainer: {
    flex: 1,
    backgroundColor: "white",
    padding: 15,
    borderRadius: 99,
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#b66feb",
    elevation: 5,
    width: "50%",
  },
  selectDateContainer: {
    flex: 1,
    backgroundColor: "#b66feb",
    padding: 13,
    borderRadius: 99,
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#b66feb",
    elevation: 5,
    width: "50%",
  },
  selectDayContainer: {
    flex: 1,
    backgroundColor: "#b66feb",
    padding: 15,
    borderRadius: 99,
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#b66feb",
    elevation: 5,
    width: "90%",
    left: 10,
    right: 10,
  },
  centerView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "red",
    borderRadius: 20,
    width: "90%",
    padding: 35,
    alignItems: "center",
    ShadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  selectedTime: {
    padding: 10,
    borderWidth: 1,
    borderRadius: 99,
    paddingHorizontal: 15,
    borderColor: "#ab32ff",
    backgroundColor: "#b66feb",
    color: "#ffffff",
    fontWeight: "bold",
  },
  unselectedTime: {
    padding: 10,
    borderWidth: 1,
    borderRadius: 99,
    paddingHorizontal: 15,
    borderColor: "#b66feb",
    color: "#b66feb",
  },
  noteTextArea: {
    borderWidth: 1,
    borderRadius: 15,
    textAlignVertical: "top",
    padding: 20,
    fontSize: 17,
    fontWeight: "bold",
    borderColor: "#b66feb",
  },
  confirmBtn: {
    textAlign: "center",
    padding: 10,
    backgroundColor: "#b66feb",
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
    borderRadius: 99,
    elevation: 2, //make shadown
  },

  // Profile
  profileDiv: {
    width: "100%",
    height: "43%",
    position: "relative",
    padding: 0,
    margin: 0,
  },
  profileText: {
    backgroundColor: "#b94aff",
    height: "60%",
    position: "relative",
  },
  profileImgDiv: {
    backgroundColor: "#ffffff",
    position: "absolute",
    top: "25%",
    left: 20,
    right: 20,
    height: "60%",
    borderRadius: 20,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    elevation: 70,
  },
  profileIcons: {
    height: 50,
    width: 50,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#b94aff",
    borderRadius: 30,
    zIndex: 1,
  },
};
